export const LOAD_STAFFS = "LOAD_STAFFS";
export const STAFFS_LOADING = 'STAFFS_LOADING'
export const STAFFS_LOADING_FAILED = 'STAFFS_LOADING_FAILED'
export const ADD_NEW_EMPLOYEE = "ADD_NEW_EMPLOYEE";
export const LOAD_DEPARTMENTS = "LOAD_DEPARTMENTS";
export const LOAD_STAFF_SALARY = "ADD_STAFF_SALARY";
